### ISSUE TITLE
Possible to wrap into Component instead of view for the example?

### ISSUE THREAD

**Issue by kithokit** [Wildhoney/EmberDroplet#74] opened 2014-12-08 10:55 UTC

**Comment by g-cassie** [comment] 2015-02-20 20:41
@Wildhoney I'm just taking a look at this for my own project and there doesn't seem to be a simple path forward.  You can use the DropletController mixin in a component.  The problem is that DropletView expects certain properties to be stored on its controller.  I haven't experimented with anything yet but my initial instinct is to pull the functionality of DropletView into a mixin.  We can then provide DropletView and DropletComponent with substantially the same functionality.

I think it will be important to do something because best practice as broadcasted from the Ember core team seems to be to stop using views and controllers and instead just use components.

I would be happy to submit a PR to get this going but I don't think the changes would be trivial.  Let me know if you are open to this approach and I can proceed with a first cut at this.

**Comment by tibotiber** [comment] 2015-05-18 14:00
I'm very interested in this too. It seems inevitable to keep EmberDroplet relevant...
As anyone made progress on the topic?

**Comment by Wildhoney** [comment] 2015-05-18 22:15
Agreed that we need to first place this into an `Ember.Mixin` and then we can use it in an `Ember.Component` and an `Ember.View` for backwards compatibility. It's on my list of todos :+1:

**Comment by Kuzirashi** [comment] 2015-06-13 12:59
I think EmberDroplet should follow example of other Ember addons - you should support older versions of Ember only until some point, which would be marked as release. I'm writing this because `Ember.CoreView, Ember.View, Ember.ContainerView and Ember.CollectionView` will be dropped in Ember 2.0 and raise deprecations in Ember 1.13. This addon is very good and it would be nice if it would take component approach when 2.0 becomes stable release. Good luck with project.

**Comment by devlo** [comment] 2015-07-01 14:10
As @Kuzirashi said, views will be dropped in Ember 2.0 which will arrive soon, any plans for migrating to component ? It's important question for anyone that is using 1.13 and have plans to upgrade to 2.0.

**Comment by Wildhoney** [comment] 2015-07-01 14:24
I'll move it over to an `Ember.Component` once I find the time :+1: It's definitely on the cards, and I know how to implement it.

**Comment by devlo** [comment] 2015-07-01 14:29
Good to know, i hope it will arrive before/around the time 2.0 will come. Thx for your work.

**Comment by Wildhoney** [comment] 2015-08-14 12:45
[See PR](https://github.com/Wildhoney/EmberDroplet/pull/89) which will be merged soon :+1: If you have any comments, please post them in the PR.

**Closed by Wildhoney** 2015-08-14 12:45 UTC
Labels: enhancement
